// Generated by tools/make_voice.py. Do not edit by hand.
window.AUDIO_FILES = {
"c-fx-r1": {
"url": "audio/c-fx-r1.m4a",
"voice": "af_heart",
"h": "a457841a658e"
},
"c-fx-r2": {
"url": "audio/c-fx-r2.m4a",
"voice": "af_heart",
"h": "834e43a3c421"
},
"c-fx-turn": {
"url": "audio/c-fx-turn.m4a",
"voice": "af_heart",
"h": "005704466643"
},
"c-fx-good": {
"url": "audio/c-fx-good.m4a",
"voice": "af_heart",
"h": "008c8fc7e7af"
},
"c-fx-pace": {
"url": "audio/c-fx-pace.m4a",
"voice": "af_heart",
"h": "1963a79f763d"
},
"c-fx-pause": {
"url": "audio/c-fx-pause.m4a",
"voice": "af_heart",
"h": "df7505be2737"
},
"c-fx-end": {
"url": "audio/c-fx-end.m4a",
"voice": "af_heart",
"h": "f58cf053d1a2"
},
"c-fx-nospeech": {
"url": "audio/c-fx-nospeech.m4a",
"voice": "af_heart",
"h": "23909beea78b"
},
"c-fx-done1": {
"url": "audio/c-fx-done1.m4a",
"voice": "af_heart",
"h": "2251e1d6c477"
},
"c-fx-done2": {
"url": "audio/c-fx-done2.m4a",
"voice": "af_heart",
"h": "27559e0ec604"
},
"c-fx-quiz": {
"url": "audio/c-fx-quiz.m4a",
"voice": "af_heart",
"h": "22442dacd2a4"
},
"c-fx-best": {
"url": "audio/c-fx-best.m4a",
"voice": "af_heart",
"h": "83b540d56421"
},
"c-fx-risky": {
"url": "audio/c-fx-risky.m4a",
"voice": "af_heart",
"h": "fde1ebd102a3"
},
"c-fx-notway": {
"url": "audio/c-fx-notway.m4a",
"voice": "af_heart",
"h": "be5a325ccffa"
},
"c-fx-right": {
"url": "audio/c-fx-right.m4a",
"voice": "af_heart",
"h": "e9e7e1d9ff00"
},
"c-fx-wrong": {
"url": "audio/c-fx-wrong.m4a",
"voice": "af_heart",
"h": "cd871b500d9a"
},
"c-fx-say": {
"url": "audio/c-fx-say.m4a",
"voice": "af_heart",
"h": "bf0f1396ba6f"
},
"c-fx-ldone": {
"url": "audio/c-fx-ldone.m4a",
"voice": "af_heart",
"h": "c61c18983d9c"
},
"c-fx-breathe": {
"url": "audio/c-fx-breathe.m4a",
"voice": "af_heart",
"h": "e15fb227138c"
},
"c-at0-intro": {
"url": "audio/c-at0-intro.m4a",
"voice": "af_heart",
"h": "7557acbcee32"
},
"c-at0-pq0": {
"url": "audio/c-at0-pq0.m4a",
"voice": "af_heart",
"h": "21271582c36b"
},
"c-at0-pq0-why": {
"url": "audio/c-at0-pq0-why.m4a",
"voice": "af_heart",
"h": "4fd18c33faad"
},
"c-at0-pq1": {
"url": "audio/c-at0-pq1.m4a",
"voice": "af_heart",
"h": "bc4bde293e9c"
},
"c-at0-pq1-why": {
"url": "audio/c-at0-pq1-why.m4a",
"voice": "af_heart",
"h": "4eb9beab7068"
},
"c-at0-s0": {
"url": "audio/c-at0-s0.m4a",
"voice": "af_heart",
"h": "904be8f05d95"
},
"c-at0-s1": {
"url": "audio/c-at0-s1.m4a",
"voice": "af_heart",
"h": "fd91a063c252"
},
"c-lesson0-ask": {
"url": "audio/c-lesson0-ask.m4a",
"voice": "af_heart",
"h": "6c21a10a5031"
},
"qz0-a": {
"url": "audio/qz0-a.m4a",
"voice": "af_heart",
"h": "b12438e8d55b"
},
"qz0-b": {
"url": "audio/qz0-b.m4a",
"voice": "af_heart",
"h": "0ea48332aeeb"
},
"c-lesson0-p0-note": {
"url": "audio/c-lesson0-p0-note.m4a",
"voice": "af_heart",
"h": "690a42f47e0e"
},
"c-at0-s1-r0": {
"url": "audio/c-at0-s1-r0.m4a",
"voice": "af_heart",
"h": "308969b2845d"
},
"c-at0-s2": {
"url": "audio/c-at0-s2.m4a",
"voice": "af_heart",
"h": "c8af827248f0"
},
"c-at0-s2-r0": {
"url": "audio/c-at0-s2-r0.m4a",
"voice": "af_heart",
"h": "fadbd223d4ca"
},
"c-at0-s2-r1": {
"url": "audio/c-at0-s2-r1.m4a",
"voice": "af_heart",
"h": "6af8eee9d98f"
},
"c-at0-s2-r2": {
"url": "audio/c-at0-s2-r2.m4a",
"voice": "af_heart",
"h": "ca1f53305aaa"
},
"c-at0-rp": {
"url": "audio/c-at0-rp.m4a",
"voice": "af_heart",
"h": "0786a92f9ff3"
},
"at0-t0-c0": {
"url": "audio/at0-t0-c0.m4a",
"voice": "am_fenrir",
"h": "5e0ba18831e9"
},
"at0-t0": {
"url": "audio/at0-t0.m4a",
"voice": "am_michael",
"h": "8e2aaab1b5fd"
},
"at0-t1-c0": {
"url": "audio/at0-t1-c0.m4a",
"voice": "am_fenrir",
"h": "d3589a5eedb6"
},
"at0-t1": {
"url": "audio/at0-t1.m4a",
"voice": "am_michael",
"h": "8427c1ed195c"
},
"at0-t2-c0": {
"url": "audio/at0-t2-c0.m4a",
"voice": "am_fenrir",
"h": "6cab468bfda0"
},
"at0-t2": {
"url": "audio/at0-t2.m4a",
"voice": "am_michael",
"h": "7cb2d978f8c5"
},
"at0-t3": {
"url": "audio/at0-t3.m4a",
"voice": "am_michael",
"h": "12d248ad1b83"
},
"c-at0-db": {
"url": "audio/c-at0-db.m4a",
"voice": "af_heart",
"h": "d3514e9c661d"
},
"c-lesson0-q0": {
"url": "audio/c-lesson0-q0.m4a",
"voice": "af_heart",
"h": "e3e2d87ffe5e"
},
"c-lesson0-q0-why": {
"url": "audio/c-lesson0-q0-why.m4a",
"voice": "af_heart",
"h": "873834c5b6e7"
},
"qz0-0-o0": {
"url": "audio/qz0-0-o0.m4a",
"voice": "af_heart",
"h": "9a9ba4d29703"
},
"qz0-0-o1": {
"url": "audio/qz0-0-o1.m4a",
"voice": "af_heart",
"h": "39d210e02794"
},
"qz0-0-o2": {
"url": "audio/qz0-0-o2.m4a",
"voice": "af_heart",
"h": "fc4b1400cae6"
},
"qz0-0-o3": {
"url": "audio/qz0-0-o3.m4a",
"voice": "af_heart",
"h": "4059150a1615"
},
"c-lesson0-q1": {
"url": "audio/c-lesson0-q1.m4a",
"voice": "af_heart",
"h": "de6d545dfffd"
},
"c-lesson0-q1-why": {
"url": "audio/c-lesson0-q1-why.m4a",
"voice": "af_heart",
"h": "850f1c69adb1"
},
"qz0-1-o0": {
"url": "audio/qz0-1-o0.m4a",
"voice": "af_heart",
"h": "946f42b682ff"
},
"qz0-1-o1": {
"url": "audio/qz0-1-o1.m4a",
"voice": "af_heart",
"h": "2ed07a40db2b"
},
"qz0-1-o2": {
"url": "audio/qz0-1-o2.m4a",
"voice": "af_heart",
"h": "1a05b49379c7"
},
"qz0-1-o3": {
"url": "audio/qz0-1-o3.m4a",
"voice": "af_heart",
"h": "a3a3f1985b31"
},
"c-lesson0-q2": {
"url": "audio/c-lesson0-q2.m4a",
"voice": "af_heart",
"h": "674fad0745bd"
},
"c-lesson0-q2-why": {
"url": "audio/c-lesson0-q2-why.m4a",
"voice": "af_heart",
"h": "681ae8203eb1"
},
"qz0-2-o0": {
"url": "audio/qz0-2-o0.m4a",
"voice": "af_heart",
"h": "cce411a57e0e"
},
"qz0-2-o1": {
"url": "audio/qz0-2-o1.m4a",
"voice": "af_heart",
"h": "574bb5c311e0"
},
"qz0-2-o2": {
"url": "audio/qz0-2-o2.m4a",
"voice": "af_heart",
"h": "c97a66459cfd"
},
"qz0-2-o3": {
"url": "audio/qz0-2-o3.m4a",
"voice": "af_heart",
"h": "e833d2a1d171"
},
"c-lesson0-q3": {
"url": "audio/c-lesson0-q3.m4a",
"voice": "af_heart",
"h": "8ba42f9125ad"
},
"c-lesson0-q3-why": {
"url": "audio/c-lesson0-q3-why.m4a",
"voice": "af_heart",
"h": "2f03b230eb05"
},
"qz0-3-o0": {
"url": "audio/qz0-3-o0.m4a",
"voice": "af_heart",
"h": "493728ee95d7"
},
"qz0-3-o1": {
"url": "audio/qz0-3-o1.m4a",
"voice": "af_heart",
"h": "f4d0be17e1ad"
},
"qz0-3-o2": {
"url": "audio/qz0-3-o2.m4a",
"voice": "af_heart",
"h": "99e27f485d3d"
},
"qz0-3-o3": {
"url": "audio/qz0-3-o3.m4a",
"voice": "af_heart",
"h": "61a28900a672"
},
"c-at0-rf": {
"url": "audio/c-at0-rf.m4a",
"voice": "af_heart",
"h": "451eeb70c7fc"
},
"c-at1-intro": {
"url": "audio/c-at1-intro.m4a",
"voice": "af_heart",
"h": "3f527a3bc56f"
},
"c-at1-pq0": {
"url": "audio/c-at1-pq0.m4a",
"voice": "af_heart",
"h": "8d12fee8a465"
},
"c-at1-pq0-why": {
"url": "audio/c-at1-pq0-why.m4a",
"voice": "af_heart",
"h": "4e4cc4009fbf"
},
"c-at1-pq1": {
"url": "audio/c-at1-pq1.m4a",
"voice": "af_heart",
"h": "bd9c19319665"
},
"c-at1-pq1-why": {
"url": "audio/c-at1-pq1-why.m4a",
"voice": "af_heart",
"h": "f18c128e7cf4"
},
"c-at1-s0": {
"url": "audio/c-at1-s0.m4a",
"voice": "af_heart",
"h": "a7665548b509"
},
"c-at1-s1": {
"url": "audio/c-at1-s1.m4a",
"voice": "af_heart",
"h": "832bd5887102"
},
"c-at1-s2": {
"url": "audio/c-at1-s2.m4a",
"voice": "af_heart",
"h": "cd5627c0f3d0"
},
"c-at1-s2-r0": {
"url": "audio/c-at1-s2-r0.m4a",
"voice": "af_heart",
"h": "16ed45130624"
},
"c-at1-rp": {
"url": "audio/c-at1-rp.m4a",
"voice": "af_heart",
"h": "52b3a30fbc48"
},
"at1-t0-c0": {
"url": "audio/at1-t0-c0.m4a",
"voice": "am_fenrir",
"h": "0f6827b36ea9"
},
"at1-t0": {
"url": "audio/at1-t0.m4a",
"voice": "am_michael",
"h": "766ccecdd69f"
},
"at1-t1": {
"url": "audio/at1-t1.m4a",
"voice": "am_michael",
"h": "4a9e18492c9f"
},
"at1-t2-c0": {
"url": "audio/at1-t2-c0.m4a",
"voice": "am_fenrir",
"h": "5bccaa6c03b8"
},
"at1-t2": {
"url": "audio/at1-t2.m4a",
"voice": "am_michael",
"h": "8090598dae2c"
},
"at1-t3": {
"url": "audio/at1-t3.m4a",
"voice": "am_michael",
"h": "930ec31e07b9"
},
"c-at1-db": {
"url": "audio/c-at1-db.m4a",
"voice": "af_heart",
"h": "753e85cdab0e"
},
"c-lesson1-q0": {
"url": "audio/c-lesson1-q0.m4a",
"voice": "af_heart",
"h": "bd620a450f71"
},
"c-lesson1-q0-why": {
"url": "audio/c-lesson1-q0-why.m4a",
"voice": "af_heart",
"h": "e2a314a0a364"
},
"qz1-0-o0": {
"url": "audio/qz1-0-o0.m4a",
"voice": "af_heart",
"h": "d1a0bc7a0438"
},
"qz1-0-o1": {
"url": "audio/qz1-0-o1.m4a",
"voice": "af_heart",
"h": "5846b246b5ef"
},
"qz1-0-o2": {
"url": "audio/qz1-0-o2.m4a",
"voice": "af_heart",
"h": "e430888238c5"
},
"qz1-0-o3": {
"url": "audio/qz1-0-o3.m4a",
"voice": "af_heart",
"h": "c11973e927b3"
},
"c-lesson1-q1": {
"url": "audio/c-lesson1-q1.m4a",
"voice": "af_heart",
"h": "e8b7ee73eddd"
},
"c-lesson1-q1-why": {
"url": "audio/c-lesson1-q1-why.m4a",
"voice": "af_heart",
"h": "2cfa987f32f1"
},
"qz1-1-o0": {
"url": "audio/qz1-1-o0.m4a",
"voice": "af_heart",
"h": "2bc6ba80c470"
},
"qz1-1-o1": {
"url": "audio/qz1-1-o1.m4a",
"voice": "af_heart",
"h": "a1259c5315f1"
},
"qz1-1-o2": {
"url": "audio/qz1-1-o2.m4a",
"voice": "af_heart",
"h": "f71b8982a54b"
},
"qz1-1-o3": {
"url": "audio/qz1-1-o3.m4a",
"voice": "af_heart",
"h": "dfa17f6d1013"
},
"c-lesson1-q2": {
"url": "audio/c-lesson1-q2.m4a",
"voice": "af_heart",
"h": "fc90e6ac9c13"
},
"c-lesson1-q2-why": {
"url": "audio/c-lesson1-q2-why.m4a",
"voice": "af_heart",
"h": "363f18b832ad"
},
"qz1-2-o0": {
"url": "audio/qz1-2-o0.m4a",
"voice": "af_heart",
"h": "5ac4ae96f593"
},
"qz1-2-o1": {
"url": "audio/qz1-2-o1.m4a",
"voice": "af_heart",
"h": "9ab08384b60f"
},
"qz1-2-o2": {
"url": "audio/qz1-2-o2.m4a",
"voice": "af_heart",
"h": "95d56f1fc0a6"
},
"qz1-2-o3": {
"url": "audio/qz1-2-o3.m4a",
"voice": "af_heart",
"h": "1df4e01b5539"
},
"c-lesson1-q3": {
"url": "audio/c-lesson1-q3.m4a",
"voice": "af_heart",
"h": "38b1e89ed82b"
},
"c-lesson1-q3-why": {
"url": "audio/c-lesson1-q3-why.m4a",
"voice": "af_heart",
"h": "d68cc1605dab"
},
"qz1-3-o0": {
"url": "audio/qz1-3-o0.m4a",
"voice": "af_heart",
"h": "5d1e53b028ff"
},
"qz1-3-o1": {
"url": "audio/qz1-3-o1.m4a",
"voice": "af_heart",
"h": "e7d85a74b97b"
},
"qz1-3-o2": {
"url": "audio/qz1-3-o2.m4a",
"voice": "af_heart",
"h": "e984b8404c23"
},
"qz1-3-o3": {
"url": "audio/qz1-3-o3.m4a",
"voice": "af_heart",
"h": "ebd05f0c9bf9"
},
"c-at1-rf": {
"url": "audio/c-at1-rf.m4a",
"voice": "af_heart",
"h": "9db9c6fbaf2e"
},
"c-at2-intro": {
"url": "audio/c-at2-intro.m4a",
"voice": "af_heart",
"h": "5b1486e0ae30"
},
"c-at2-pq0": {
"url": "audio/c-at2-pq0.m4a",
"voice": "af_heart",
"h": "960f50c1969e"
},
"c-at2-pq0-why": {
"url": "audio/c-at2-pq0-why.m4a",
"voice": "af_heart",
"h": "c8cfa6e70e0f"
},
"c-at2-pq1": {
"url": "audio/c-at2-pq1.m4a",
"voice": "af_heart",
"h": "e0dbc43974a1"
},
"c-at2-pq1-why": {
"url": "audio/c-at2-pq1-why.m4a",
"voice": "af_heart",
"h": "b36ba3a35e29"
},
"c-at2-s0": {
"url": "audio/c-at2-s0.m4a",
"voice": "af_heart",
"h": "630ac8a3ff9b"
},
"c-at2-s1": {
"url": "audio/c-at2-s1.m4a",
"voice": "af_heart",
"h": "815a0e786089"
},
"c-at2-s1-r0": {
"url": "audio/c-at2-s1-r0.m4a",
"voice": "af_heart",
"h": "e9105e7fa682"
},
"c-at2-s1-r1": {
"url": "audio/c-at2-s1-r1.m4a",
"voice": "af_heart",
"h": "028c89e5ebab"
},
"c-at2-s1-r2": {
"url": "audio/c-at2-s1-r2.m4a",
"voice": "af_heart",
"h": "0cdc54aa77de"
},
"c-at2-s2": {
"url": "audio/c-at2-s2.m4a",
"voice": "af_heart",
"h": "7fc7c8f09917"
},
"c-at2-s2-r0": {
"url": "audio/c-at2-s2-r0.m4a",
"voice": "af_heart",
"h": "8a4dba1b59b2"
},
"c-at2-s2-r1": {
"url": "audio/c-at2-s2-r1.m4a",
"voice": "af_heart",
"h": "0ab2fe476a2d"
},
"c-at2-s2-r2": {
"url": "audio/c-at2-s2-r2.m4a",
"voice": "af_heart",
"h": "f272c46d8856"
},
"c-at2-s2-r3": {
"url": "audio/c-at2-s2-r3.m4a",
"voice": "af_heart",
"h": "4b3e2a832373"
},
"c-at2-rp": {
"url": "audio/c-at2-rp.m4a",
"voice": "af_heart",
"h": "6e943f15e300"
},
"at2-t0-c0": {
"url": "audio/at2-t0-c0.m4a",
"voice": "am_fenrir",
"h": "0fa42b045f1e"
},
"at2-t0": {
"url": "audio/at2-t0.m4a",
"voice": "am_michael",
"h": "ed2b38fcb934"
},
"at2-t1-c0": {
"url": "audio/at2-t1-c0.m4a",
"voice": "am_fenrir",
"h": "56938e592665"
},
"at2-t1": {
"url": "audio/at2-t1.m4a",
"voice": "am_michael",
"h": "55c4ec33c1b3"
},
"at2-t2-c0": {
"url": "audio/at2-t2-c0.m4a",
"voice": "am_fenrir",
"h": "d393cc027295"
},
"at2-t2": {
"url": "audio/at2-t2.m4a",
"voice": "am_michael",
"h": "a73773dd5227"
},
"at2-t3": {
"url": "audio/at2-t3.m4a",
"voice": "am_michael",
"h": "000998fd1d2a"
},
"c-at2-db": {
"url": "audio/c-at2-db.m4a",
"voice": "af_heart",
"h": "893ea0a96f59"
},
"c-lesson2-q0": {
"url": "audio/c-lesson2-q0.m4a",
"voice": "af_heart",
"h": "99191c6bc5e5"
},
"c-lesson2-q0-why": {
"url": "audio/c-lesson2-q0-why.m4a",
"voice": "af_heart",
"h": "b17b953960c5"
},
"qz2-0-o0": {
"url": "audio/qz2-0-o0.m4a",
"voice": "af_heart",
"h": "0585bdbc1d9e"
},
"qz2-0-o1": {
"url": "audio/qz2-0-o1.m4a",
"voice": "af_heart",
"h": "ff6f8e97f957"
},
"qz2-0-o2": {
"url": "audio/qz2-0-o2.m4a",
"voice": "af_heart",
"h": "d2b7ccf3b646"
},
"qz2-0-o3": {
"url": "audio/qz2-0-o3.m4a",
"voice": "af_heart",
"h": "82abe2999a47"
},
"c-lesson2-q1": {
"url": "audio/c-lesson2-q1.m4a",
"voice": "af_heart",
"h": "95186df09650"
},
"c-lesson2-q1-why": {
"url": "audio/c-lesson2-q1-why.m4a",
"voice": "af_heart",
"h": "d9e1c3e1bc13"
},
"qz2-1-o0": {
"url": "audio/qz2-1-o0.m4a",
"voice": "af_heart",
"h": "f590ddc0148c"
},
"qz2-1-o1": {
"url": "audio/qz2-1-o1.m4a",
"voice": "af_heart",
"h": "c880c058a766"
},
"qz2-1-o2": {
"url": "audio/qz2-1-o2.m4a",
"voice": "af_heart",
"h": "7ebf25298ae2"
},
"qz2-1-o3": {
"url": "audio/qz2-1-o3.m4a",
"voice": "af_heart",
"h": "32b29fe3e0ee"
},
"c-lesson2-q2": {
"url": "audio/c-lesson2-q2.m4a",
"voice": "af_heart",
"h": "9487d8d840cd"
},
"c-lesson2-q2-why": {
"url": "audio/c-lesson2-q2-why.m4a",
"voice": "af_heart",
"h": "1bd94ccee81f"
},
"qz2-2-o0": {
"url": "audio/qz2-2-o0.m4a",
"voice": "af_heart",
"h": "f713a1fb450a"
},
"qz2-2-o1": {
"url": "audio/qz2-2-o1.m4a",
"voice": "af_heart",
"h": "b8ce28fe34d5"
},
"qz2-2-o2": {
"url": "audio/qz2-2-o2.m4a",
"voice": "af_heart",
"h": "b8d8ac227a38"
},
"qz2-2-o3": {
"url": "audio/qz2-2-o3.m4a",
"voice": "af_heart",
"h": "6b247a846115"
},
"c-lesson2-q3": {
"url": "audio/c-lesson2-q3.m4a",
"voice": "af_heart",
"h": "bc75e57a64f6"
},
"c-lesson2-q3-why": {
"url": "audio/c-lesson2-q3-why.m4a",
"voice": "af_heart",
"h": "d0e52ac8d9cf"
},
"qz2-3-o0": {
"url": "audio/qz2-3-o0.m4a",
"voice": "af_heart",
"h": "c01ab20927a9"
},
"qz2-3-o1": {
"url": "audio/qz2-3-o1.m4a",
"voice": "af_heart",
"h": "6ed6f73f2d0c"
},
"qz2-3-o2": {
"url": "audio/qz2-3-o2.m4a",
"voice": "af_heart",
"h": "d5d795659994"
},
"qz2-3-o3": {
"url": "audio/qz2-3-o3.m4a",
"voice": "af_heart",
"h": "4528ef68e6df"
},
"c-lesson2-q4": {
"url": "audio/c-lesson2-q4.m4a",
"voice": "af_heart",
"h": "7ec99808235f"
},
"c-lesson2-q4-why": {
"url": "audio/c-lesson2-q4-why.m4a",
"voice": "af_heart",
"h": "44720763749f"
},
"qz2-4-o0": {
"url": "audio/qz2-4-o0.m4a",
"voice": "af_heart",
"h": "4dd30cb69904"
},
"qz2-4-o1": {
"url": "audio/qz2-4-o1.m4a",
"voice": "af_heart",
"h": "64c26da39b52"
},
"qz2-4-o2": {
"url": "audio/qz2-4-o2.m4a",
"voice": "af_heart",
"h": "69f13dc152ed"
},
"qz2-4-o3": {
"url": "audio/qz2-4-o3.m4a",
"voice": "af_heart",
"h": "2622a565bb58"
},
"c-at2-rf": {
"url": "audio/c-at2-rf.m4a",
"voice": "af_heart",
"h": "04788afd8e6b"
},
"c-at3-intro": {
"url": "audio/c-at3-intro.m4a",
"voice": "af_heart",
"h": "0f7e870c55db"
},
"c-at3-pq0": {
"url": "audio/c-at3-pq0.m4a",
"voice": "af_heart",
"h": "ee13886a980f"
},
"c-at3-pq0-why": {
"url": "audio/c-at3-pq0-why.m4a",
"voice": "af_heart",
"h": "36a584808db6"
},
"c-at3-s0": {
"url": "audio/c-at3-s0.m4a",
"voice": "af_heart",
"h": "4adcae7d654d"
},
"c-at3-s1": {
"url": "audio/c-at3-s1.m4a",
"voice": "af_heart",
"h": "a7c102a7d7e3"
},
"c-at3-s2": {
"url": "audio/c-at3-s2.m4a",
"voice": "af_heart",
"h": "cef597717cda"
},
"c-at3-s2-r0": {
"url": "audio/c-at3-s2-r0.m4a",
"voice": "af_heart",
"h": "49478330b211"
},
"c-at3-s2-r1": {
"url": "audio/c-at3-s2-r1.m4a",
"voice": "af_heart",
"h": "0c5126717671"
},
"c-at3-s2-r2": {
"url": "audio/c-at3-s2-r2.m4a",
"voice": "af_heart",
"h": "b090a7c04a83"
},
"c-at3-s2-r3": {
"url": "audio/c-at3-s2-r3.m4a",
"voice": "af_heart",
"h": "18f3a4204154"
},
"c-at3-s2-r4": {
"url": "audio/c-at3-s2-r4.m4a",
"voice": "af_heart",
"h": "e0c9870eef41"
},
"c-at3-s3": {
"url": "audio/c-at3-s3.m4a",
"voice": "af_heart",
"h": "5a139528b1e0"
},
"c-at3-rp": {
"url": "audio/c-at3-rp.m4a",
"voice": "af_heart",
"h": "a545151df399"
},
"at3-t0-c0": {
"url": "audio/at3-t0-c0.m4a",
"voice": "am_fenrir",
"h": "c0609359da1e"
},
"at3-t0": {
"url": "audio/at3-t0.m4a",
"voice": "am_michael",
"h": "4f44dd022340"
},
"at3-t1-c0": {
"url": "audio/at3-t1-c0.m4a",
"voice": "am_fenrir",
"h": "341de1379bd1"
},
"at3-t1": {
"url": "audio/at3-t1.m4a",
"voice": "am_michael",
"h": "c2717912001b"
},
"at3-t2-c0": {
"url": "audio/at3-t2-c0.m4a",
"voice": "am_fenrir",
"h": "57d23114329c"
},
"at3-t2": {
"url": "audio/at3-t2.m4a",
"voice": "am_michael",
"h": "466a9554daf9"
},
"at3-t3": {
"url": "audio/at3-t3.m4a",
"voice": "am_michael",
"h": "7690673f7dfc"
},
"c-at3-db": {
"url": "audio/c-at3-db.m4a",
"voice": "af_heart",
"h": "6a9f88255688"
},
"c-lesson3-q0": {
"url": "audio/c-lesson3-q0.m4a",
"voice": "af_heart",
"h": "48d756c5e9be"
},
"c-lesson3-q0-why": {
"url": "audio/c-lesson3-q0-why.m4a",
"voice": "af_heart",
"h": "2616aac10e3b"
},
"qz3-0-o0": {
"url": "audio/qz3-0-o0.m4a",
"voice": "af_heart",
"h": "f2dfd94c3552"
},
"qz3-0-o1": {
"url": "audio/qz3-0-o1.m4a",
"voice": "af_heart",
"h": "1e4df84afdb9"
},
"qz3-0-o2": {
"url": "audio/qz3-0-o2.m4a",
"voice": "af_heart",
"h": "253cb32450f1"
},
"qz3-0-o3": {
"url": "audio/qz3-0-o3.m4a",
"voice": "af_heart",
"h": "6b3b41a405e5"
},
"c-lesson3-q1": {
"url": "audio/c-lesson3-q1.m4a",
"voice": "af_heart",
"h": "f6bc31c37f50"
},
"c-lesson3-q1-why": {
"url": "audio/c-lesson3-q1-why.m4a",
"voice": "af_heart",
"h": "39306e4962ea"
},
"qz3-1-o0": {
"url": "audio/qz3-1-o0.m4a",
"voice": "af_heart",
"h": "46ae30824064"
},
"qz3-1-o1": {
"url": "audio/qz3-1-o1.m4a",
"voice": "af_heart",
"h": "335e86f8a81f"
},
"qz3-1-o2": {
"url": "audio/qz3-1-o2.m4a",
"voice": "af_heart",
"h": "55ccecf53409"
},
"qz3-1-o3": {
"url": "audio/qz3-1-o3.m4a",
"voice": "af_heart",
"h": "1bcf1e7d30d8"
},
"c-lesson3-q2": {
"url": "audio/c-lesson3-q2.m4a",
"voice": "af_heart",
"h": "073e60a5a6f4"
},
"c-lesson3-q2-why": {
"url": "audio/c-lesson3-q2-why.m4a",
"voice": "af_heart",
"h": "efb5ee2976a7"
},
"qz3-2-o0": {
"url": "audio/qz3-2-o0.m4a",
"voice": "af_heart",
"h": "1869855a4778"
},
"qz3-2-o1": {
"url": "audio/qz3-2-o1.m4a",
"voice": "af_heart",
"h": "2a5820a898ed"
},
"qz3-2-o2": {
"url": "audio/qz3-2-o2.m4a",
"voice": "af_heart",
"h": "c9e8c5a1e518"
},
"qz3-2-o3": {
"url": "audio/qz3-2-o3.m4a",
"voice": "af_heart",
"h": "d5d829645602"
},
"c-lesson3-q3": {
"url": "audio/c-lesson3-q3.m4a",
"voice": "af_heart",
"h": "8642413fc289"
},
"c-lesson3-q3-why": {
"url": "audio/c-lesson3-q3-why.m4a",
"voice": "af_heart",
"h": "e3ca7f0c839f"
},
"qz3-3-o0": {
"url": "audio/qz3-3-o0.m4a",
"voice": "af_heart",
"h": "bd03b3719e89"
},
"qz3-3-o1": {
"url": "audio/qz3-3-o1.m4a",
"voice": "af_heart",
"h": "a4ef9312ccac"
},
"qz3-3-o2": {
"url": "audio/qz3-3-o2.m4a",
"voice": "af_heart",
"h": "335e86f8a81f"
},
"qz3-3-o3": {
"url": "audio/qz3-3-o3.m4a",
"voice": "af_heart",
"h": "4b23ecaaa509"
},
"c-at3-rf": {
"url": "audio/c-at3-rf.m4a",
"voice": "af_heart",
"h": "aeccbe36a44e"
},
"c-at5-intro": {
"url": "audio/c-at5-intro.m4a",
"voice": "af_heart",
"h": "7e33105581df"
},
"c-at5-pq0": {
"url": "audio/c-at5-pq0.m4a",
"voice": "af_heart",
"h": "393878d281bf"
},
"c-at5-pq0-why": {
"url": "audio/c-at5-pq0-why.m4a",
"voice": "af_heart",
"h": "da7578a38272"
},
"c-at5-pq1": {
"url": "audio/c-at5-pq1.m4a",
"voice": "af_heart",
"h": "4673796d56e0"
},
"c-at5-pq1-why": {
"url": "audio/c-at5-pq1-why.m4a",
"voice": "af_heart",
"h": "56f832088719"
},
"c-at5-s0": {
"url": "audio/c-at5-s0.m4a",
"voice": "af_heart",
"h": "69795ac6dccd"
},
"c-lesson5-ask": {
"url": "audio/c-lesson5-ask.m4a",
"voice": "af_heart",
"h": "441bc45ba35d"
},
"qz5-a": {
"url": "audio/qz5-a.m4a",
"voice": "af_heart",
"h": "7f0f92e52de1"
},
"qz5-b": {
"url": "audio/qz5-b.m4a",
"voice": "af_heart",
"h": "91af74282eb0"
},
"c-lesson5-p0-note": {
"url": "audio/c-lesson5-p0-note.m4a",
"voice": "af_heart",
"h": "5e35c485be84"
},
"c-at5-s0-r0": {
"url": "audio/c-at5-s0-r0.m4a",
"voice": "af_heart",
"h": "693002655847"
},
"c-at5-s1": {
"url": "audio/c-at5-s1.m4a",
"voice": "af_heart",
"h": "374958c407d2"
},
"c-at5-s1-r0": {
"url": "audio/c-at5-s1-r0.m4a",
"voice": "af_heart",
"h": "58a3e4c83e13"
},
"c-at5-rp": {
"url": "audio/c-at5-rp.m4a",
"voice": "af_heart",
"h": "0273c4a9c129"
},
"at5-t0-c0": {
"url": "audio/at5-t0-c0.m4a",
"voice": "am_fenrir",
"h": "f761e9b7a5bf"
},
"at5-t0": {
"url": "audio/at5-t0.m4a",
"voice": "am_michael",
"h": "bab1447a7d0a"
},
"at5-t1-c0": {
"url": "audio/at5-t1-c0.m4a",
"voice": "am_fenrir",
"h": "aa21665a1e2b"
},
"at5-t1": {
"url": "audio/at5-t1.m4a",
"voice": "am_michael",
"h": "9cf0ac6dfef9"
},
"c-at5-db": {
"url": "audio/c-at5-db.m4a",
"voice": "af_heart",
"h": "bb10e27fffde"
},
"c-lesson5-q0": {
"url": "audio/c-lesson5-q0.m4a",
"voice": "af_heart",
"h": "135d3bf2b3d8"
},
"c-lesson5-q0-why": {
"url": "audio/c-lesson5-q0-why.m4a",
"voice": "af_heart",
"h": "1324e96c8772"
},
"qz5-0-o0": {
"url": "audio/qz5-0-o0.m4a",
"voice": "af_heart",
"h": "8574173e0fab"
},
"qz5-0-o1": {
"url": "audio/qz5-0-o1.m4a",
"voice": "af_heart",
"h": "9c76b9a39ac2"
},
"qz5-0-o2": {
"url": "audio/qz5-0-o2.m4a",
"voice": "af_heart",
"h": "98d6d4e51a6f"
},
"c-lesson5-q1": {
"url": "audio/c-lesson5-q1.m4a",
"voice": "af_heart",
"h": "5b2f816e58f1"
},
"c-lesson5-q1-why": {
"url": "audio/c-lesson5-q1-why.m4a",
"voice": "af_heart",
"h": "1af0c0f47ef4"
},
"qz5-1-o0": {
"url": "audio/qz5-1-o0.m4a",
"voice": "af_heart",
"h": "21a4e2c2f499"
},
"qz5-1-o1": {
"url": "audio/qz5-1-o1.m4a",
"voice": "af_heart",
"h": "fd6c737eab5e"
},
"qz5-1-o2": {
"url": "audio/qz5-1-o2.m4a",
"voice": "af_heart",
"h": "a02448e64b0d"
},
"c-at5-rf": {
"url": "audio/c-at5-rf.m4a",
"voice": "af_heart",
"h": "a865ef215d8a"
},
"c-at6-intro": {
"url": "audio/c-at6-intro.m4a",
"voice": "af_heart",
"h": "0b33560e64bc"
},
"c-at6-pq0": {
"url": "audio/c-at6-pq0.m4a",
"voice": "af_heart",
"h": "611949ac5c83"
},
"c-at6-pq0-why": {
"url": "audio/c-at6-pq0-why.m4a",
"voice": "af_heart",
"h": "08f7120aaac1"
},
"c-at6-s0": {
"url": "audio/c-at6-s0.m4a",
"voice": "af_heart",
"h": "e915aca73781"
},
"c-lesson6-ask": {
"url": "audio/c-lesson6-ask.m4a",
"voice": "af_heart",
"h": "9203b7043d5b"
},
"qz6-a": {
"url": "audio/qz6-a.m4a",
"voice": "af_heart",
"h": "fed08950de14"
},
"qz6-b": {
"url": "audio/qz6-b.m4a",
"voice": "af_heart",
"h": "12b6b64a85c6"
},
"c-lesson6-p0-note": {
"url": "audio/c-lesson6-p0-note.m4a",
"voice": "af_heart",
"h": "4692872c85d7"
},
"c-at6-s0-r0": {
"url": "audio/c-at6-s0-r0.m4a",
"voice": "af_heart",
"h": "f83e47d5b29f"
},
"c-at6-s1": {
"url": "audio/c-at6-s1.m4a",
"voice": "af_heart",
"h": "241553c4a270"
},
"c-at6-s1-r0": {
"url": "audio/c-at6-s1-r0.m4a",
"voice": "af_heart",
"h": "e6c0ba34cfef"
},
"c-at6-rp": {
"url": "audio/c-at6-rp.m4a",
"voice": "af_heart",
"h": "48dde04467fd"
},
"at6-t0-c0": {
"url": "audio/at6-t0-c0.m4a",
"voice": "am_fenrir",
"h": "35e87f1120ab"
},
"at6-t0": {
"url": "audio/at6-t0.m4a",
"voice": "am_michael",
"h": "1aa233b059dd"
},
"at6-t1-c0": {
"url": "audio/at6-t1-c0.m4a",
"voice": "am_fenrir",
"h": "1c3457408f66"
},
"at6-t1": {
"url": "audio/at6-t1.m4a",
"voice": "am_michael",
"h": "8774412057dd"
},
"c-at6-db": {
"url": "audio/c-at6-db.m4a",
"voice": "af_heart",
"h": "a08106a45c7a"
},
"c-lesson6-q0": {
"url": "audio/c-lesson6-q0.m4a",
"voice": "af_heart",
"h": "f292a53c4c91"
},
"c-lesson6-q0-why": {
"url": "audio/c-lesson6-q0-why.m4a",
"voice": "af_heart",
"h": "033952905dd1"
},
"qz6-0-o0": {
"url": "audio/qz6-0-o0.m4a",
"voice": "af_heart",
"h": "dbaf36e70a56"
},
"qz6-0-o1": {
"url": "audio/qz6-0-o1.m4a",
"voice": "af_heart",
"h": "ea07e37181b1"
},
"qz6-0-o2": {
"url": "audio/qz6-0-o2.m4a",
"voice": "af_heart",
"h": "6f1cf571df49"
},
"c-lesson6-q1": {
"url": "audio/c-lesson6-q1.m4a",
"voice": "af_heart",
"h": "e67b0bdeb8b3"
},
"c-lesson6-q1-why": {
"url": "audio/c-lesson6-q1-why.m4a",
"voice": "af_heart",
"h": "089404f0408d"
},
"qz6-1-o0": {
"url": "audio/qz6-1-o0.m4a",
"voice": "af_heart",
"h": "a4ba56ea0c44"
},
"qz6-1-o1": {
"url": "audio/qz6-1-o1.m4a",
"voice": "af_heart",
"h": "bea1701bd881"
},
"qz6-1-o2": {
"url": "audio/qz6-1-o2.m4a",
"voice": "af_heart",
"h": "a7c06beafd42"
},
"c-at6-rf": {
"url": "audio/c-at6-rf.m4a",
"voice": "af_heart",
"h": "9b6736318c18"
},
"c-at7-intro": {
"url": "audio/c-at7-intro.m4a",
"voice": "af_heart",
"h": "0c3c55991e0e"
},
"c-at7-s0": {
"url": "audio/c-at7-s0.m4a",
"voice": "af_heart",
"h": "5a3f55950dfa"
},
"c-lesson7-ask": {
"url": "audio/c-lesson7-ask.m4a",
"voice": "af_heart",
"h": "62a8b28a65a8"
},
"qz7-a": {
"url": "audio/qz7-a.m4a",
"voice": "af_heart",
"h": "4766fb35aa7c"
},
"qz7-b": {
"url": "audio/qz7-b.m4a",
"voice": "af_heart",
"h": "e2c3440c167c"
},
"c-lesson7-p0-note": {
"url": "audio/c-lesson7-p0-note.m4a",
"voice": "af_heart",
"h": "39c8935a17e1"
},
"c-at7-s0-r0": {
"url": "audio/c-at7-s0-r0.m4a",
"voice": "af_heart",
"h": "69276bbfd2ac"
},
"c-at7-rp": {
"url": "audio/c-at7-rp.m4a",
"voice": "af_heart",
"h": "2cb03b358c1f"
},
"at7-t0-c0": {
"url": "audio/at7-t0-c0.m4a",
"voice": "am_fenrir",
"h": "546c043f91ac"
},
"at7-t0": {
"url": "audio/at7-t0.m4a",
"voice": "am_michael",
"h": "1c1d277d370a"
},
"at7-t1-c0": {
"url": "audio/at7-t1-c0.m4a",
"voice": "am_fenrir",
"h": "1526c3a74806"
},
"at7-t1": {
"url": "audio/at7-t1.m4a",
"voice": "am_michael",
"h": "9483c65acfb0"
},
"c-at7-db": {
"url": "audio/c-at7-db.m4a",
"voice": "af_heart",
"h": "f5938e14f9e1"
},
"c-lesson7-q0": {
"url": "audio/c-lesson7-q0.m4a",
"voice": "af_heart",
"h": "f101aeb99b5b"
},
"c-lesson7-q0-why": {
"url": "audio/c-lesson7-q0-why.m4a",
"voice": "af_heart",
"h": "ead3d5a66a57"
},
"qz7-0-t": {
"url": "audio/qz7-0-t.m4a",
"voice": "am_michael",
"h": "e1a5d50b934a"
},
"c-lesson7-q1": {
"url": "audio/c-lesson7-q1.m4a",
"voice": "af_heart",
"h": "798fc0ecb8c1"
},
"c-lesson7-q1-why": {
"url": "audio/c-lesson7-q1-why.m4a",
"voice": "af_heart",
"h": "96ca2103290d"
},
"qz7-1-t": {
"url": "audio/qz7-1-t.m4a",
"voice": "am_michael",
"h": "62c6c16f2f22"
},
"c-at7-rf": {
"url": "audio/c-at7-rf.m4a",
"voice": "af_heart",
"h": "da00b57a6fe9"
},
"c-at8-intro": {
"url": "audio/c-at8-intro.m4a",
"voice": "af_heart",
"h": "1dfb63773c65"
},
"c-at8-pq0": {
"url": "audio/c-at8-pq0.m4a",
"voice": "af_heart",
"h": "5254ad2df462"
},
"c-at8-pq0-why": {
"url": "audio/c-at8-pq0-why.m4a",
"voice": "af_heart",
"h": "1939ea664aa3"
},
"c-at8-pq1": {
"url": "audio/c-at8-pq1.m4a",
"voice": "af_heart",
"h": "43a0490f7b1b"
},
"c-at8-pq1-why": {
"url": "audio/c-at8-pq1-why.m4a",
"voice": "af_heart",
"h": "b9829b8046d8"
},
"c-at8-s0": {
"url": "audio/c-at8-s0.m4a",
"voice": "af_heart",
"h": "129b8fd9da1e"
},
"c-lesson8-ask": {
"url": "audio/c-lesson8-ask.m4a",
"voice": "af_heart",
"h": "b1cac323831c"
},
"qz8-a": {
"url": "audio/qz8-a.m4a",
"voice": "af_heart",
"h": "2d57ea6ffb47"
},
"qz8-b": {
"url": "audio/qz8-b.m4a",
"voice": "af_heart",
"h": "e8061f958f70"
},
"c-lesson8-p0-note": {
"url": "audio/c-lesson8-p0-note.m4a",
"voice": "af_heart",
"h": "4e3ee5c581f2"
},
"c-at8-s0-r0": {
"url": "audio/c-at8-s0-r0.m4a",
"voice": "af_heart",
"h": "f85d87f5afec"
},
"c-at8-rp": {
"url": "audio/c-at8-rp.m4a",
"voice": "af_heart",
"h": "f44d5671ed8a"
},
"at8-t0-c0": {
"url": "audio/at8-t0-c0.m4a",
"voice": "am_fenrir",
"h": "c0a0670d92a2"
},
"at8-t0": {
"url": "audio/at8-t0.m4a",
"voice": "am_michael",
"h": "a0b5f52b06eb"
},
"at8-t1-c0": {
"url": "audio/at8-t1-c0.m4a",
"voice": "am_fenrir",
"h": "432003d267e2"
},
"at8-t1": {
"url": "audio/at8-t1.m4a",
"voice": "am_michael",
"h": "cf9c975c930f"
},
"c-at8-db": {
"url": "audio/c-at8-db.m4a",
"voice": "af_heart",
"h": "71589ec70ea4"
},
"c-lesson8-q0": {
"url": "audio/c-lesson8-q0.m4a",
"voice": "af_heart",
"h": "df5d9b2c3feb"
},
"c-lesson8-q0-why": {
"url": "audio/c-lesson8-q0-why.m4a",
"voice": "af_heart",
"h": "409c2c09b258"
},
"qz8-0-t": {
"url": "audio/qz8-0-t.m4a",
"voice": "am_michael",
"h": "ae57fdeaa68d"
},
"c-lesson8-q1": {
"url": "audio/c-lesson8-q1.m4a",
"voice": "af_heart",
"h": "ecfce27d472d"
},
"c-lesson8-q1-why": {
"url": "audio/c-lesson8-q1-why.m4a",
"voice": "af_heart",
"h": "c1dead987290"
},
"qz8-1-o0": {
"url": "audio/qz8-1-o0.m4a",
"voice": "af_heart",
"h": "a905201dc93a"
},
"qz8-1-o1": {
"url": "audio/qz8-1-o1.m4a",
"voice": "af_heart",
"h": "4ba9c8c3dbf4"
},
"qz8-1-o2": {
"url": "audio/qz8-1-o2.m4a",
"voice": "af_heart",
"h": "3ce06e3d2cac"
},
"c-at8-rf": {
"url": "audio/c-at8-rf.m4a",
"voice": "af_heart",
"h": "0cbea5c8da86"
},
"c-at9-intro": {
"url": "audio/c-at9-intro.m4a",
"voice": "af_heart",
"h": "9538d711d20e"
},
"c-at9-s0": {
"url": "audio/c-at9-s0.m4a",
"voice": "af_heart",
"h": "4ecdfd7c4ce5"
},
"c-lesson9-ask": {
"url": "audio/c-lesson9-ask.m4a",
"voice": "af_heart",
"h": "2ebad69ade56"
},
"qz9-a": {
"url": "audio/qz9-a.m4a",
"voice": "af_heart",
"h": "0d574f471f87"
},
"qz9-b": {
"url": "audio/qz9-b.m4a",
"voice": "af_heart",
"h": "6f2541156ee3"
},
"c-lesson9-p0-note": {
"url": "audio/c-lesson9-p0-note.m4a",
"voice": "af_heart",
"h": "5119fb2151fb"
},
"c-at9-s0-r0": {
"url": "audio/c-at9-s0-r0.m4a",
"voice": "af_heart",
"h": "eb8d8982df3c"
},
"c-at9-rp": {
"url": "audio/c-at9-rp.m4a",
"voice": "af_heart",
"h": "787d5192c192"
},
"at9-t0-c0": {
"url": "audio/at9-t0-c0.m4a",
"voice": "am_fenrir",
"h": "e4a27170dc26"
},
"at9-t0": {
"url": "audio/at9-t0.m4a",
"voice": "am_michael",
"h": "3bd9e48bb06c"
},
"at9-t1-c0": {
"url": "audio/at9-t1-c0.m4a",
"voice": "am_fenrir",
"h": "81f39f9f2f98"
},
"at9-t1": {
"url": "audio/at9-t1.m4a",
"voice": "am_michael",
"h": "1ab17bd19c64"
},
"c-at9-db": {
"url": "audio/c-at9-db.m4a",
"voice": "af_heart",
"h": "fc5e1c3254ed"
},
"c-lesson9-q0": {
"url": "audio/c-lesson9-q0.m4a",
"voice": "af_heart",
"h": "7bc1f1c958c1"
},
"c-lesson9-q0-why": {
"url": "audio/c-lesson9-q0-why.m4a",
"voice": "af_heart",
"h": "357b1d5e5170"
},
"qz9-0-t": {
"url": "audio/qz9-0-t.m4a",
"voice": "am_michael",
"h": "9749d42113e4"
},
"c-lesson9-q1": {
"url": "audio/c-lesson9-q1.m4a",
"voice": "af_heart",
"h": "1edd8c22efd1"
},
"c-lesson9-q1-why": {
"url": "audio/c-lesson9-q1-why.m4a",
"voice": "af_heart",
"h": "43bcfa8a0362"
},
"qz9-1-o0": {
"url": "audio/qz9-1-o0.m4a",
"voice": "af_heart",
"h": "e4af0b4699ec"
},
"qz9-1-o1": {
"url": "audio/qz9-1-o1.m4a",
"voice": "af_heart",
"h": "812d3ced1017"
},
"qz9-1-o2": {
"url": "audio/qz9-1-o2.m4a",
"voice": "af_heart",
"h": "113e301db75b"
},
"c-at9-rf": {
"url": "audio/c-at9-rf.m4a",
"voice": "af_heart",
"h": "10a8adb8884f"
},
"c-at10-intro": {
"url": "audio/c-at10-intro.m4a",
"voice": "af_heart",
"h": "8f8989838a99"
},
"c-at10-s0": {
"url": "audio/c-at10-s0.m4a",
"voice": "af_heart",
"h": "40b553840350"
},
"c-lesson10-ask": {
"url": "audio/c-lesson10-ask.m4a",
"voice": "af_heart",
"h": "042b49cb0047"
},
"qz10-a": {
"url": "audio/qz10-a.m4a",
"voice": "af_heart",
"h": "43613a01f254"
},
"qz10-b": {
"url": "audio/qz10-b.m4a",
"voice": "af_heart",
"h": "37641cda4b49"
},
"c-lesson10-p0-note": {
"url": "audio/c-lesson10-p0-note.m4a",
"voice": "af_heart",
"h": "b2ac17dd4ae4"
},
"c-at10-s0-r0": {
"url": "audio/c-at10-s0-r0.m4a",
"voice": "af_heart",
"h": "e893742b03d5"
},
"c-at10-rp": {
"url": "audio/c-at10-rp.m4a",
"voice": "af_heart",
"h": "c6925c4b0a01"
},
"at10-t0-c0": {
"url": "audio/at10-t0-c0.m4a",
"voice": "am_fenrir",
"h": "6d8dd3817740"
},
"at10-t0": {
"url": "audio/at10-t0.m4a",
"voice": "am_michael",
"h": "f3958429415e"
},
"at10-t1-c0": {
"url": "audio/at10-t1-c0.m4a",
"voice": "am_fenrir",
"h": "630bef1c9dfb"
},
"at10-t1": {
"url": "audio/at10-t1.m4a",
"voice": "am_michael",
"h": "71770e0e4625"
},
"c-at10-db": {
"url": "audio/c-at10-db.m4a",
"voice": "af_heart",
"h": "befc88c36d92"
},
"c-lesson10-q0": {
"url": "audio/c-lesson10-q0.m4a",
"voice": "af_heart",
"h": "d1375adf570b"
},
"c-lesson10-q0-why": {
"url": "audio/c-lesson10-q0-why.m4a",
"voice": "af_heart",
"h": "b54b815c354a"
},
"qz10-0-t": {
"url": "audio/qz10-0-t.m4a",
"voice": "am_michael",
"h": "7a08582fe396"
},
"c-lesson10-q1": {
"url": "audio/c-lesson10-q1.m4a",
"voice": "af_heart",
"h": "4f517234511c"
},
"c-lesson10-q1-why": {
"url": "audio/c-lesson10-q1-why.m4a",
"voice": "af_heart",
"h": "4ba6555b3587"
},
"qz10-1-o0": {
"url": "audio/qz10-1-o0.m4a",
"voice": "af_heart",
"h": "104dbb7b7e0a"
},
"qz10-1-o1": {
"url": "audio/qz10-1-o1.m4a",
"voice": "af_heart",
"h": "59c5f91f698f"
},
"qz10-1-o2": {
"url": "audio/qz10-1-o2.m4a",
"voice": "af_heart",
"h": "66e7c8da451a"
},
"c-at10-rf": {
"url": "audio/c-at10-rf.m4a",
"voice": "af_heart",
"h": "7d8821d287b1"
},
"c-at11-intro": {
"url": "audio/c-at11-intro.m4a",
"voice": "af_heart",
"h": "7749784957cc"
},
"c-dc11-s0": {
"url": "audio/c-dc11-s0.m4a",
"voice": "af_heart",
"h": "6c3b1b68062b"
},
"c-dc11-s0-o0": {
"url": "audio/c-dc11-s0-o0.m4a",
"voice": "af_heart",
"h": "428c025bd0c1"
},
"c-dc11-s0-o1": {
"url": "audio/c-dc11-s0-o1.m4a",
"voice": "af_heart",
"h": "4c433c271f07"
},
"c-dc11-s0-o2": {
"url": "audio/c-dc11-s0-o2.m4a",
"voice": "af_heart",
"h": "7370f3936e95"
},
"c-dc11-s1": {
"url": "audio/c-dc11-s1.m4a",
"voice": "af_heart",
"h": "60552e5ca3c4"
},
"c-dc11-s1-o0": {
"url": "audio/c-dc11-s1-o0.m4a",
"voice": "af_heart",
"h": "8b2ad04dc585"
},
"c-dc11-s1-o1": {
"url": "audio/c-dc11-s1-o1.m4a",
"voice": "af_heart",
"h": "b89bedebdcee"
},
"c-dc11-s1-o2": {
"url": "audio/c-dc11-s1-o2.m4a",
"voice": "af_heart",
"h": "c13109c39046"
},
"c-dc11-pr": {
"url": "audio/c-dc11-pr.m4a",
"voice": "af_heart",
"h": "7323a111568e"
},
"c-at12-intro": {
"url": "audio/c-at12-intro.m4a",
"voice": "af_heart",
"h": "82fa5862afe2"
},
"c-dc12-s0": {
"url": "audio/c-dc12-s0.m4a",
"voice": "af_heart",
"h": "b8480db9e737"
},
"c-dc12-s0-o0": {
"url": "audio/c-dc12-s0-o0.m4a",
"voice": "af_heart",
"h": "2d7d9df00b4e"
},
"c-dc12-s0-o1": {
"url": "audio/c-dc12-s0-o1.m4a",
"voice": "af_heart",
"h": "36dfca910f28"
},
"c-dc12-s0-o2": {
"url": "audio/c-dc12-s0-o2.m4a",
"voice": "af_heart",
"h": "da3ecc958690"
},
"c-dc12-s1": {
"url": "audio/c-dc12-s1.m4a",
"voice": "af_heart",
"h": "f24b3bd4a292"
},
"c-dc12-s1-o0": {
"url": "audio/c-dc12-s1-o0.m4a",
"voice": "af_heart",
"h": "d87085c50738"
},
"c-dc12-s1-o1": {
"url": "audio/c-dc12-s1-o1.m4a",
"voice": "af_heart",
"h": "d05b3dcb29a4"
},
"c-dc12-s1-o2": {
"url": "audio/c-dc12-s1-o2.m4a",
"voice": "af_heart",
"h": "91d5b897c361"
},
"c-dc12-pr": {
"url": "audio/c-dc12-pr.m4a",
"voice": "af_heart",
"h": "080af56d2637"
},
"c-at13-intro": {
"url": "audio/c-at13-intro.m4a",
"voice": "af_heart",
"h": "7692b84d812f"
},
"c-dc13-s0": {
"url": "audio/c-dc13-s0.m4a",
"voice": "af_heart",
"h": "d1d269075bb3"
},
"c-dc13-s0-o0": {
"url": "audio/c-dc13-s0-o0.m4a",
"voice": "af_heart",
"h": "ab9ef0ef5f7f"
},
"c-dc13-s0-o1": {
"url": "audio/c-dc13-s0-o1.m4a",
"voice": "af_heart",
"h": "c30808d71015"
},
"c-dc13-s0-o2": {
"url": "audio/c-dc13-s0-o2.m4a",
"voice": "af_heart",
"h": "fb66ab95397b"
},
"c-dc13-s1": {
"url": "audio/c-dc13-s1.m4a",
"voice": "af_heart",
"h": "2259b64d6721"
},
"c-dc13-s1-o0": {
"url": "audio/c-dc13-s1-o0.m4a",
"voice": "af_heart",
"h": "713f51c94606"
},
"c-dc13-s1-o1": {
"url": "audio/c-dc13-s1-o1.m4a",
"voice": "af_heart",
"h": "6b23c0161f0b"
},
"c-dc13-s1-o2": {
"url": "audio/c-dc13-s1-o2.m4a",
"voice": "af_heart",
"h": "f0809fe8c348"
},
"c-dc13-pr": {
"url": "audio/c-dc13-pr.m4a",
"voice": "af_heart",
"h": "02a2e04767ee"
},
"c-at14-intro": {
"url": "audio/c-at14-intro.m4a",
"voice": "af_heart",
"h": "7caca836244a"
},
"c-dc14-s0": {
"url": "audio/c-dc14-s0.m4a",
"voice": "af_heart",
"h": "3ac241a972f4"
},
"c-dc14-s0-o0": {
"url": "audio/c-dc14-s0-o0.m4a",
"voice": "af_heart",
"h": "845127935804"
},
"c-dc14-s0-o1": {
"url": "audio/c-dc14-s0-o1.m4a",
"voice": "af_heart",
"h": "48d1c65ff541"
},
"c-dc14-s0-o2": {
"url": "audio/c-dc14-s0-o2.m4a",
"voice": "af_heart",
"h": "4d650eccebbe"
},
"c-dc14-pr": {
"url": "audio/c-dc14-pr.m4a",
"voice": "af_heart",
"h": "d51d88d80cc4"
},
"c-at15-intro": {
"url": "audio/c-at15-intro.m4a",
"voice": "af_heart",
"h": "609bff13cbdf"
},
"c-dc15-s0": {
"url": "audio/c-dc15-s0.m4a",
"voice": "af_heart",
"h": "bc879ab5a656"
},
"c-dc15-s0-o0": {
"url": "audio/c-dc15-s0-o0.m4a",
"voice": "af_heart",
"h": "706a9180cfb1"
},
"c-dc15-s0-o1": {
"url": "audio/c-dc15-s0-o1.m4a",
"voice": "af_heart",
"h": "664820b16882"
},
"c-dc15-s0-o2": {
"url": "audio/c-dc15-s0-o2.m4a",
"voice": "af_heart",
"h": "0b0fa942240e"
},
"c-dc15-pr": {
"url": "audio/c-dc15-pr.m4a",
"voice": "af_heart",
"h": "c7dba7d4a0dc"
},
"c-at16-intro": {
"url": "audio/c-at16-intro.m4a",
"voice": "af_heart",
"h": "a8d84ad9a91e"
},
"c-dc16-s0": {
"url": "audio/c-dc16-s0.m4a",
"voice": "af_heart",
"h": "26635d3c4f23"
},
"c-dc16-s0-o0": {
"url": "audio/c-dc16-s0-o0.m4a",
"voice": "af_heart",
"h": "0920235e2acb"
},
"c-dc16-s0-o1": {
"url": "audio/c-dc16-s0-o1.m4a",
"voice": "af_heart",
"h": "e9066bb478e5"
},
"c-dc16-s0-o2": {
"url": "audio/c-dc16-s0-o2.m4a",
"voice": "af_heart",
"h": "56f7a37d2188"
},
"c-dc16-pr": {
"url": "audio/c-dc16-pr.m4a",
"voice": "af_heart",
"h": "ef6f2c2f5abc"
}
};
